# Generated by Django 5.2.4 on 2025-07-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='monthly_income',
            field=models.IntegerField(default=0),
        ),
    ]
