# Generated by Django 5.2.4 on 2025-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
